version: "3.9"

name: ntt-banca
services:
  mysql-clientes:
    image: mysql:8.0
    container_name: mysql-clientes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: clientes_db
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql_clientes_data:/var/lib/mysql
    networks: [banca-net]

  mysql-cuentas:
    image: mysql:8.0
    container_name: mysql-cuentas
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cuentas_db
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql_cuentas_data:/var/lib/mysql
    networks: [banca-net]

  cliente-persona-ms:
    build:
      context: ./cliente-persona-ms
      dockerfile: Dockerfile
    image: cliente-persona-ms:latest
    container_name: cliente-persona-ms
    depends_on:
      mysql-clientes:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clientes:3306/clientes_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks: [banca-net]

  cuenta-movimiento-ms:
    build:
      context: ./cuenta-movimiento-ms
      dockerfile: Dockerfile
    image: cuenta-movimiento-ms:latest
    container_name: cuenta-movimiento-ms
    depends_on:
      mysql-cuentas:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cuentas:3306/cuentas_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks: [banca-net]

volumes:
  mysql_clientes_data:
  mysql_cuentas_data:

networks:
  banca-net:
    driver: bridge
