# ====== Etapa de build ======
FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn -q -DskipTests dependency:go-offline
COPY src ./src
RUN --mount=type=cache,target=/root/.m2 mvn -q -DskipTests clean package

# ====== Etapa de runtime ======
FROM eclipse-temurin:17-jre-alpine
ENV TZ=America/Guayaquil
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java","-Duser.timezone=America/Guayaquil","-jar","/app/app.jar"]
